---
title: "p8105_hw3_yl5214"
output: github_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

## Problem 2
```{r}
library(p8105.datasets)
data("brfss_smart2010")
view(brfss_smart2010)
```

```{r}
brfss=brfss_smart2010 |> 
  janitor::clean_names() |> 
  filter(topic=='Overall Health') |> 
  filter(response %in% c('Excellent', 'Very good','Good','Fair','Poor')) |> 
  mutate(
    response= factor(response, levels = c("Poor", "Fair", "Good", "Very good","Excellent"), ordered = TRUE)
  ) |> 
rename(state =locationabbr) |> 
rename(county =locationdesc)
```

## In 2002, which states were observed at 7 or more locations? What about in 2010?
```{r}
brfss_2002=brfss |> 
  filter(year=='2002') |> 
  group_by(state) |> 
  summarize(n_obs = n_distinct(county)) |> 
  filter(n_obs>=7)

brfss_2010=brfss |> 
  filter(year=='2010') |> 
  group_by(state) |> 
  summarize(n_obs = n_distinct(county)) |> 
  filter(n_obs>=7)
```
In 2002, CT, FL, MA, NC, NJ, PA were observed at 7 or more locations. In 2010, 14 states were observed at 7 or more locations.
